### ISSUE TITLE
Get instance imposible

### ISSUE THREAD

**Issue by ggface** [valdesekamdem/MaterialDesign-Toast#3]
Hi. I would like to get **Toast** instance because need call `Toast.cancel()` sometimes. I mean **MDToast.makeText** could returns **Toast** instance instead **Void**.

**Comment by valdesekamdem** [comment]
Hi @ggface thank you for using **MD-Toast** library,
i will release a version very soon which corrects this.

**Comment by valdesekamdem** [comment]
Hi @ggface happy to announce you that i just released a new version of **MDToast**
Now the **MDToast.makeText** function returns **MDToast** instance which is inherited from **Toast**.
You also have new functions in *MDToast*, you can explore them.

If you found it useful, don't hesitate to give a star to the library.
Happy coding.
